blank_issues_enabled: true
contact_links:
  - name: Ask a Question
    url: https://github.com/oyve/weather-formulas/discussions
    about: Ask questions and discuss ideas with the community
  - name: Documentation
    url: https://github.com/oyve/weather-formulas#readme
    about: Read the documentation and usage examples
